/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author 181710062
 */
public class TelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpTelaInicial = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        IMArquivo = new javax.swing.JMenu();
        IMCadastrarItens = new javax.swing.JMenuItem();
        IMSair = new javax.swing.JMenuItem();
        IMControleeGestaodeEstoque = new javax.swing.JMenu();
        IMEstoque = new javax.swing.JMenuItem();
        IMReposicao = new javax.swing.JMenuItem();
        IMItenscomDefeitoCadastrados = new javax.swing.JMenuItem();
        IMHistorico = new javax.swing.JMenu();
        IMPlanejamentodeEncomendas = new javax.swing.JMenuItem();
        IMHistoricoItens = new javax.swing.JMenuItem();
        IMAjuda = new javax.swing.JMenu();
        IMSobreaAplicacao = new javax.swing.JMenuItem();
        IMContatos = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jdpTelaInicialLayout = new javax.swing.GroupLayout(jdpTelaInicial);
        jdpTelaInicial.setLayout(jdpTelaInicialLayout);
        jdpTelaInicialLayout.setHorizontalGroup(
            jdpTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        jdpTelaInicialLayout.setVerticalGroup(
            jdpTelaInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 519, Short.MAX_VALUE)
        );

        IMArquivo.setText("Arquivo");

        IMCadastrarItens.setText("Cadastrar Itens ");
        IMCadastrarItens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMCadastrarItensActionPerformed(evt);
            }
        });
        IMArquivo.add(IMCadastrarItens);

        IMSair.setText("Sair");
        IMArquivo.add(IMSair);

        jMenuBar1.add(IMArquivo);

        IMControleeGestaodeEstoque.setText("Controle e Gestão de Estoque");

        IMEstoque.setText("Estoque");
        IMControleeGestaodeEstoque.add(IMEstoque);

        IMReposicao.setText("Reposição");
        IMReposicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMReposicaoActionPerformed(evt);
            }
        });
        IMControleeGestaodeEstoque.add(IMReposicao);

        IMItenscomDefeitoCadastrados.setText("Itens com Defeito(s) Cadastrado(s)");
        IMControleeGestaodeEstoque.add(IMItenscomDefeitoCadastrados);

        jMenuBar1.add(IMControleeGestaodeEstoque);

        IMHistorico.setText("Histórico");

        IMPlanejamentodeEncomendas.setText("Planejamento de Encomendas");
        IMHistorico.add(IMPlanejamentodeEncomendas);

        IMHistoricoItens.setText("Histórico Itens, Reposição e Defeito");
        IMHistorico.add(IMHistoricoItens);

        jMenuBar1.add(IMHistorico);

        IMAjuda.setText("Ajuda");

        IMSobreaAplicacao.setText("Sobre a Aplicação");
        IMAjuda.add(IMSobreaAplicacao);

        IMContatos.setText("Contatos");
        IMAjuda.add(IMContatos);

        jMenuBar1.add(IMAjuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelaInicial)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelaInicial)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IMReposicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMReposicaoActionPerformed
        telaReposicao obj = new telaReposicao();
        jdpTelaInicial.add( obj );
        obj.setVisible( true );
    }//GEN-LAST:event_IMReposicaoActionPerformed

    private void IMCadastrarItensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMCadastrarItensActionPerformed
        TelaCadastrarItens obj = new TelaCadastrarItens();
        jdpTelaInicial.add( obj );
        obj.setVisible( true );
    }//GEN-LAST:event_IMCadastrarItensActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu IMAjuda;
    private javax.swing.JMenu IMArquivo;
    private javax.swing.JMenuItem IMCadastrarItens;
    private javax.swing.JMenuItem IMContatos;
    private javax.swing.JMenu IMControleeGestaodeEstoque;
    private javax.swing.JMenuItem IMEstoque;
    private javax.swing.JMenu IMHistorico;
    private javax.swing.JMenuItem IMHistoricoItens;
    private javax.swing.JMenuItem IMItenscomDefeitoCadastrados;
    private javax.swing.JMenuItem IMPlanejamentodeEncomendas;
    private javax.swing.JMenuItem IMReposicao;
    private javax.swing.JMenuItem IMSair;
    private javax.swing.JMenuItem IMSobreaAplicacao;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDesktopPane jdpTelaInicial;
    // End of variables declaration//GEN-END:variables
}
